### PR TITLE
MAINT: add missing git archive export for tags

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Another packaging-only change that lets setuptools_scm know what version this was exported from the repo as.

## Motivation and Context

See https://github.com/conda-forge/qtpyinheritance-feedstock/pull/4

## How Has This Been Tested?

This works for e.g. pcdsdevices

## Where Has This Been Documented?

Only here

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by tangkong — APPROVED** [review]
This is what happens when I do the conversion manually.  LGTM

**Comment by ZLLentz** [comment]
@tangkong what do you think I should do with the conda-forge build? Remove setuptools_scm and let it merge/tag without it, then add it back in for the next tag?

Or reject the tag PR and just change the maintainers off-tag?

**Comment by tangkong** [comment]
I think we can just remove `setuptools_scm` from the feedstock for this tag, and add it back in what i imagine is an impending 0.0.4 tag?

**Comment by tangkong** [comment]
FWIW I think having a gap in the conda-forge build isn't that big of a deal in this particular case (taking the line where we reject the 0.0.3 feedstock and just make a new 0.0.4 feedstock)

**Comment by ZLLentz** [comment]
I'll take a similar line where we have a slightly-wrong 0.0.3 build and then don't bother tagging until we realize this makes a big difference

**Comment by ZLLentz** [comment]
Ugh, something more fundamental is broken with the forge build
I'm tempted to just close it and try again with the next version but first I'm going to try to understand it
I think we can merge this though

**Pull request merged**
